import Link from "next/link";
import { prisma } from "@/lib/db";
export default async function Home(){
 const services=await prisma.service.findMany({where:{active:true},orderBy:{sortOrder:"asc"},take:6});
 const maps="https://www.google.com/maps/search/?api=1&query=Falcon+Auto+Fix+Unit+7+120+Falcon+Street+London+Ontario+N5W+4Z1";
 return <>
 <section className="hero"><div className="container heroGrid"><div><p className="eyebrow">LONDON, ONTARIO • LOCAL AUTO REPAIR</p><h1>QUALITY SERVICE.<br/><span>KEEPING YOU ON THE ROAD.</span></h1><p className="lead">Repairs, diagnostics, maintenance, tires, brakes and oil changes from Falcon Auto Fix.</p><div className="actions"><Link className="button" href="/book">Book an Appointment</Link><a className="button ghost" href="tel:+15486899097">Call (548) 689-9097</a></div></div><div className="heroCard logoHeroCard"><img src="/falcon-logo.jpg" alt="Falcon Auto Fix logo" className="heroLogo"/><span className="badge">Now booking</span><h2>Reliable automotive service in London.</h2><p>Tell us what your vehicle needs. Pick a time. We’ll confirm your appointment.</p><div className="metric"><strong>Unit 7 - 120 Falcon Street</strong><span>London, ON N5W 4Z1</span></div><div className="metric"><strong>Book online or call</strong><span>(548) 689-9097</span></div></div></div></section>
 <section className="section flyerSection"><div className="container flyerGrid"><div><p className="eyebrow">CURRENT SERVICES & DEALS</p><h2>See what Falcon Auto Fix offers.</h2><p className="lead">Open the shop flyer for service highlights, current deals and the free multi-point inspection with any paid service.</p><div className="actions"><Link className="button" href="/book">Book an Appointment</Link><a className="button ghost" href="tel:+15486899097">Call the Shop</a></div></div><a className="flyerFrame" href="/falcon-flyer.png" target="_blank" rel="noreferrer" aria-label="Open Falcon Auto Fix flyer full size"><img src="/falcon-flyer.png" alt="Falcon Auto Fix services, deals and contact information flyer" className="flyerImage"/></a></div></section>
 <section className="section"><div className="container"><p className="eyebrow">SERVICES</p><h2>Everything your vehicle needs.</h2><div className="cards">{services.map(s=><article className="card" key={s.id}><h3>{s.name}</h3><p>{s.description}</p></article>)}</div><Link className="textLink" href="/services">View all services →</Link></div></section>
 <section className="section trustSection"><div className="container trustGrid"><div><p className="eyebrow">LOCAL & TRUSTED</p><h2>See Falcon Auto Fix on Google.</h2><p className="lead">Read customer feedback, get directions, or leave a review after your visit.</p><div className="actions"><a className="button" href="https://www.google.com/search?q=Falcon+Auto+Fix+London+Ontario" target="_blank" rel="noreferrer">Google Reviews</a><a className="button ghost" href={maps} target="_blank" rel="noreferrer">Get Directions</a></div></div><div className="reviewCard"><div className="stars" aria-label="Five stars">★★★★★</div><h3>Your experience matters.</h3><p>Had a good visit? Reviews help local customers find the shop and help Falcon Auto Fix grow.</p><a className="textLink" href="https://www.google.com/search?q=Falcon+Auto+Fix+London+Ontario" target="_blank" rel="noreferrer">Find us on Google →</a></div></div></section>
 <section className="section mapSection"><div className="container mapGrid"><div><p className="eyebrow">VISIT THE SHOP</p><h2>Unit 7 - 120 Falcon Street</h2><p>London, Ontario N5W 4Z1</p><p className="muted">Tap the map for directions.</p></div><a className="mapEmbed" href={maps} target="_blank" rel="noreferrer"><iframe title="Falcon Auto Fix map" src="https://www.google.com/maps?q=Unit%207%20120%20Falcon%20Street%20London%20Ontario%20N5W%204Z1&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></a></div></section>
 <section className="section dark"><div className="container split"><div><p className="eyebrow">HOW IT WORKS</p><h2>Booking should be the easy part.</h2><p className="bookingDisclaimer">Appointment requests are not confirmed until approved by Falcon Auto Fix. Service needs and final costs may vary after vehicle inspection.</p></div><ol className="steps"><li><b>01</b><span>Choose your service</span></li><li><b>02</b><span>Add vehicle details</span></li><li><b>03</b><span>Pick an available time</span></li><li><b>04</b><span>We confirm your appointment</span></li></ol></div></section>
 <div className="mobileSticky"><a href="tel:+15486899097">Call Now</a><Link href="/book">Book Appointment</Link></div>
 </>}
