import Link from "next/link";
import { prisma } from "@/lib/db";
export default async function Home(){
 const services=await prisma.service.findMany({where:{active:true},orderBy:{sortOrder:"asc"},take:6});
 return <>
 <section className="hero"><div className="container heroGrid"><div><p className="eyebrow">LONDON, ONTARIO • LOCAL AUTO REPAIR</p><h1>QUALITY SERVICE.<br/><span>KEEPING YOU ON THE ROAD.</span></h1><p className="lead">Repairs, diagnostics, maintenance, tires, brakes and oil changes from certified technicians at Falcon Auto Fix.</p><div className="actions"><Link className="button" href="/book">Book an Appointment</Link><a className="button ghost" href="tel:+15486899097">Call (548) 689-9097</a></div></div><div className="heroCard logoHeroCard"><img src="/falcon-logo.jpg" alt="Falcon Auto Fix logo" className="heroLogo"/><span className="badge">Now booking</span><h2>Reliable automotive service in London.</h2><p>Tell us what your vehicle needs. Pick a time. We’ll confirm your appointment.</p><div className="metric"><strong>Unit 7 - 120 Falcon Street</strong><span>London, ON N5W 4Z1</span></div><div className="metric"><strong>Mon–Fri</strong><span>8 AM–8 PM</span></div></div></div></section>
 <section className="section flyerSection"><div className="container flyerGrid"><div><p className="eyebrow">CURRENT SERVICES & DEALS</p><h2>See what Falcon Auto Fix offers.</h2><p className="lead">Check out our shop flyer for service highlights, current deals and our free multi-point inspection with any paid service.</p><div className="actions"><Link className="button" href="/book">Book an Appointment</Link><a className="button ghost" href="tel:+15486899097">Call the Shop</a></div></div><a className="flyerFrame" href="/falcon-flyer.jpg" target="_blank" rel="noreferrer" aria-label="Open Falcon Auto Fix flyer full size"><img src="/falcon-flyer.jpg" alt="Falcon Auto Fix services, deals and contact information flyer" className="flyerImage"/></a></div></section>
 <section className="section"><div className="container"><p className="eyebrow">SERVICES</p><h2>Everything your vehicle needs.</h2><div className="cards">{services.map(s=><article className="card" key={s.id}><h3>{s.name}</h3><p>{s.description}</p><span>{s.durationMinutes} min booking window</span></article>)}</div><Link className="textLink" href="/services">View all services →</Link></div></section>
 <section className="section dark"><div className="container split"><div><p className="eyebrow">HOW IT WORKS</p><h2>Booking should be the easy part.</h2></div><ol className="steps"><li><b>01</b><span>Choose your service</span></li><li><b>02</b><span>Add vehicle details</span></li><li><b>03</b><span>Pick an available time</span></li><li><b>04</b><span>We confirm your appointment</span></li></ol></div></section>
 </>}
