"use client";
import { useEffect, useMemo, useState } from "react";
type Service={id:string;name:string;description:string;durationMinutes:number};
type Form={serviceId:string;date:string;time:string;year:string;make:string;model:string;mileage:string;plate:string;vin:string;description:string;name:string;phone:string;email:string};
const init:Form={serviceId:"",date:"",time:"",year:"",make:"",model:"",mileage:"",plate:"",vin:"",description:"",name:"",phone:"",email:""};
export function BookingForm({services,defaultService}:{services:Service[];defaultService?:string}){
 const [step,setStep]=useState(1),[form,setForm]=useState<Form>({...init,serviceId:defaultService||""}),[slots,setSlots]=useState<string[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[done,setDone]=useState<{id:string}|null>(null);
 const selected=useMemo(()=>services.find(s=>s.id===form.serviceId),[services,form.serviceId]);
 useEffect(()=>{if(!form.date||!form.serviceId){setSlots([]);return;} setForm(f=>({...f,time:""})); fetch(`/api/availability?date=${form.date}&serviceId=${form.serviceId}`).then(r=>r.json()).then(d=>setSlots(d.slots||[]));},[form.date,form.serviceId]);
 const update=(k:keyof Form,v:string)=>setForm(f=>({...f,[k]:v}));
 function next(){setError(""); if(step===1&&!form.serviceId)return setError("Choose a service."); if(step===2&&(!form.year||!form.make||!form.model))return setError("Add your vehicle year, make and model."); if(step===3&&(!form.date||!form.time))return setError("Choose an available date and time."); setStep(s=>Math.min(5,s+1));}
 async function submit(){setError(""); if(!form.name||!form.phone)return setError("Name and phone number are required."); setLoading(true); const res=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const data=await res.json(); setLoading(false); if(!res.ok)return setError(data.error||"Could not create appointment."); setDone({id:data.id});}
 if(done)return <div className="success"><div className="successIcon">✓</div><h2>Appointment request received.</h2><p>Thanks, {form.name}. Falcon Auto Fix will confirm your {selected?.name.toLowerCase()} appointment shortly.</p><div className="summary"><b>{form.date} at {form.time}</b><span>{form.year} {form.make} {form.model}</span></div></div>;
 return <div className="booking"><div className="progress">{[1,2,3,4,5].map(n=><span key={n} className={n<=step?"on":""}>{n}</span>)}</div>
 {step===1&&<div><p className="eyebrow">STEP 1</p><h2>What does your vehicle need?</h2><div className="servicePicker">{services.map(s=><button type="button" className={form.serviceId===s.id?"choice selected":"choice"} onClick={()=>update("serviceId",s.id)} key={s.id}><b>{s.name}</b><small>{s.description}</small></button>)}</div></div>}
 {step===2&&<div><p className="eyebrow">STEP 2</p><h2>Tell us about the vehicle.</h2><div className="formGrid"><label>Year<input inputMode="numeric" value={form.year} onChange={e=>update("year",e.target.value)} placeholder="2019"/></label><label>Make<input value={form.make} onChange={e=>update("make",e.target.value)} placeholder="Honda"/></label><label>Model<input value={form.model} onChange={e=>update("model",e.target.value)} placeholder="Civic"/></label><label>Mileage (km)<input inputMode="numeric" value={form.mileage} onChange={e=>update("mileage",e.target.value)} placeholder="120000"/></label><label>Plate (optional)<input value={form.plate} onChange={e=>update("plate",e.target.value.toUpperCase())}/></label><label>VIN (optional)<input value={form.vin} onChange={e=>update("vin",e.target.value.toUpperCase())}/></label></div><label>What’s happening?<textarea rows={5} value={form.description} onChange={e=>update("description",e.target.value)} placeholder="Describe the symptoms, noises, warning lights, or work you want done."/></label></div>}
 {step===3&&<div><p className="eyebrow">STEP 3</p><h2>Choose an available time.</h2><label>Date<input type="date" min={new Date().toISOString().slice(0,10)} value={form.date} onChange={e=>update("date",e.target.value)}/></label>{form.date&&<div className="slots">{slots.length?slots.map(t=><button type="button" className={form.time===t?"slot selected":"slot"} onClick={()=>update("time",t)} key={t}>{t}</button>):<p>No times available for this date.</p>}</div>}</div>}
 {step===4&&<div><p className="eyebrow">STEP 4</p><h2>How can we reach you?</h2><div className="formGrid"><label>Full name<input value={form.name} onChange={e=>update("name",e.target.value)}/></label><label>Phone<input type="tel" value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label></div></div>}
 {step===5&&<div><p className="eyebrow">STEP 5</p><h2>Review your request.</h2><div className="summary"><b>{selected?.name}</b><span>{form.year} {form.make} {form.model}</span><span>{form.date} at {form.time}</span><span>{form.name} • {form.phone}</span>{form.description&&<p>{form.description}</p>}</div><p className="muted">This is an appointment request. Falcon Auto Fix will confirm it after reviewing the schedule.</p></div>}
 {error&&<p className="error">{error}</p>}<div className="bookingActions">{step>1&&<button className="button ghost darkText" type="button" onClick={()=>setStep(s=>s-1)}>Back</button>}{step<5?<button className="button" type="button" onClick={next}>Continue</button>:<button disabled={loading} className="button" type="button" onClick={submit}>{loading?"Booking…":"Request Appointment"}</button>}</div>
 </div>
}
